"""Acceptance Probe module for PatchPilot verification.

This module provides acceptance probe functionality for model-generated
verification scripts that test specific aspects of code changes without
becoming part of the patch itself.

Probes support:
- Function input/output validation
- Exception handling verification
- State change detection
- Invariant checking
- Return structure validation

Probes are:
- Generated by models with structured output
- Validated using AST whitelist checking
- Executed in temporary directories
- Run both before and after changes
- Kept separate from the patch
"""

from patchpilot.verification.probes.runner import ProbeRunner
from patchpilot.verification.probes.schema import (
    AcceptanceProbe,
    ProbeExecutionResult,
    ProbeStep,
    ProbeType,
    StepResult,
)
from patchpilot.verification.probes.validator import (
    ProbeValidationError,
    ProbeValidator,
)

__all__ = [
    "AcceptanceProbe",
    "ProbeExecutionResult",
    "ProbeRunner",
    "ProbeStep",
    "ProbeType",
    "ProbeValidationError",
    "ProbeValidator",
    "StepResult",
]
