"""RootTrace RCA contracts and artifacts.

The Demo MVP keeps the internal ``patchpilot`` package namespace for
compatibility; RCA code lives under ``patchpilot.rca``. User-facing RCA
artifacts and documentation use the RootTrace name.
"""

from patchpilot.rca.artifacts import (
    ARTIFACT_EVIDENCE_GRAPH,
    ARTIFACT_HYPOTHESES,
    ARTIFACT_INCIDENT,
    ARTIFACT_INVESTIGATION_PLAN,
    ARTIFACT_RCA_REPORT,
    ARTIFACT_VERIFICATION,
    ArtifactError,
    ArtifactWriter,
    model_to_json,
    write_artifact,
)
from patchpilot.rca.schema import (
    AgentFinding,
    AgentRole,
    CauseLink,
    ConfidenceLevel,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceItem,
    EvidenceKind,
    EvidenceRelation,
    FindingStatus,
    FixRecommendation,
    Hypothesis,
    HypothesisDisposition,
    IncidentInput,
    InvestigationPlan,
    PlanBudgets,
    PlanQuestion,
    Provenance,
    RankedCause,
    RCAReport,
    RegressionChange,
    ReportConclusion,
    SourceLocation,
    Timing,
    UncertaintyLevel,
    UncertaintySummary,
    Usage,
    VerificationOutcome,
    VerificationResult,
    VerificationStatus,
    VerificationStep,
)

__all__ = [
    "ARTIFACT_EVIDENCE_GRAPH",
    "ARTIFACT_HYPOTHESES",
    "ARTIFACT_INCIDENT",
    "ARTIFACT_INVESTIGATION_PLAN",
    "ARTIFACT_RCA_REPORT",
    "ARTIFACT_VERIFICATION",
    "AgentFinding",
    "AgentRole",
    "ArtifactError",
    "ArtifactWriter",
    "CauseLink",
    "ConfidenceLevel",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceRelation",
    "FindingStatus",
    "FixRecommendation",
    "Hypothesis",
    "HypothesisDisposition",
    "IncidentInput",
    "InvestigationPlan",
    "PlanBudgets",
    "PlanQuestion",
    "Provenance",
    "RCAReport",
    "RankedCause",
    "RegressionChange",
    "ReportConclusion",
    "SourceLocation",
    "Timing",
    "UncertaintyLevel",
    "UncertaintySummary",
    "Usage",
    "VerificationOutcome",
    "VerificationResult",
    "VerificationStatus",
    "VerificationStep",
    "model_to_json",
    "write_artifact",
]
