"""RootTrace RCA contracts and artifacts.

The Demo MVP keeps the internal ``patchpilot`` package namespace for
compatibility; RCA code lives under ``patchpilot.rca``. User-facing RCA
artifacts and documentation use the RootTrace name.
"""

from patchpilot.rca.agents import (
    CodeSpecialist,
    GitHistorySpecialist,
    IssueCISpecialist,
    LeadPlanner,
    PlanError,
    ProviderProtocol,
    SpecialistOutput,
    SpecialistResponse,
)
from patchpilot.rca.artifacts import (
    ARTIFACT_EVIDENCE_GRAPH,
    ARTIFACT_HYPOTHESES,
    ARTIFACT_INCIDENT,
    ARTIFACT_INVESTIGATION_PLAN,
    ARTIFACT_RCA_REPORT,
    ARTIFACT_VERIFICATION,
    ArtifactError,
    ArtifactWriter,
    model_to_json,
    write_artifact,
)
from patchpilot.rca.cli import (
    RcaCliResult,
    add_rca_subparser,
    run_rca_command,
    run_rca_pipeline,
)
from patchpilot.rca.context import (
    ContextTruncation,
    IncidentContext,
    IncidentSignals,
    RepositoryFingerprint,
    RepositoryInventory,
    SourceSnippet,
)
from patchpilot.rca.context_builder import (
    assert_fingerprint_unchanged,
    build_incident_context,
    build_ranked_snippets,
    build_repository_inventory,
    capture_repository_fingerprint,
    extract_signals,
)
from patchpilot.rca.history import (
    HistoricalCase,
    HistoricalCorpus,
    HistoricalRetriever,
    HistoryIndex,
    RetrievalHints,
    RetrievedCase,
    TfidfModel,
    build_history_index,
    build_tfidf,
    import_corpus,
)
from patchpilot.rca.incident_loader import (
    LoadedIncident,
    load_incident,
    resolve_base_commit,
)
from patchpilot.rca.orchestrator import (
    RcaOrchestrator,
    RcaRunResult,
    aggregate_evidence,
)
from patchpilot.rca.prompts import (
    FINAL_REPORT_SYSTEM_PROMPT,
    HYPOTHESES_SYSTEM_PROMPT,
    build_code_prompt,
    build_final_report_prompt,
    build_git_history_prompt,
    build_hypotheses_prompt,
    build_issue_ci_prompt,
    build_lead_prompt,
)
from patchpilot.rca.renderer import render_rca_markdown
from patchpilot.rca.sandbox import (
    RuntimeVerificationSandbox,
    SandboxCommandResult,
)
from patchpilot.rca.schema import (
    AgentFinding,
    AgentRole,
    CauseLink,
    ConfidenceLevel,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceItem,
    EvidenceKind,
    EvidenceRelation,
    FindingStatus,
    FixRecommendation,
    Hypothesis,
    HypothesisDisposition,
    IncidentInput,
    InvestigationPlan,
    PlanBudgets,
    PlanQuestion,
    Provenance,
    RankedCause,
    RCAReport,
    RegressionChange,
    ReportConclusion,
    SourceLocation,
    Timing,
    UncertaintyLevel,
    UncertaintySummary,
    Usage,
    VerificationOutcome,
    VerificationResult,
    VerificationStatus,
    VerificationStep,
)
from patchpilot.rca.synthesis import LeadSynthesizer, SynthesisError
from patchpilot.rca.tools import (
    GitBlameInput,
    GitHistoryInput,
    GitShowInput,
    InspectSymbolsInput,
    RcaToolRegistry,
    RcaToolResult,
    ReadExternalLogInput,
)
from patchpilot.rca.usage import UsageTracker
from patchpilot.rca.verification import RuntimeTestVerifier, VerificationRun

__all__ = [
    "ARTIFACT_EVIDENCE_GRAPH",
    "ARTIFACT_HYPOTHESES",
    "ARTIFACT_INCIDENT",
    "ARTIFACT_INVESTIGATION_PLAN",
    "ARTIFACT_RCA_REPORT",
    "ARTIFACT_VERIFICATION",
    "FINAL_REPORT_SYSTEM_PROMPT",
    "HYPOTHESES_SYSTEM_PROMPT",
    "AgentFinding",
    "AgentRole",
    "ArtifactError",
    "ArtifactWriter",
    "CauseLink",
    "CodeSpecialist",
    "ConfidenceLevel",
    "ContextTruncation",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceRelation",
    "FindingStatus",
    "FixRecommendation",
    "GitBlameInput",
    "GitHistoryInput",
    "GitHistorySpecialist",
    "GitShowInput",
    "HistoricalCase",
    "HistoricalCorpus",
    "HistoricalRetriever",
    "HistoryIndex",
    "Hypothesis",
    "HypothesisDisposition",
    "IncidentContext",
    "IncidentInput",
    "IncidentSignals",
    "InspectSymbolsInput",
    "InvestigationPlan",
    "IssueCISpecialist",
    "LeadPlanner",
    "LeadSynthesizer",
    "LoadedIncident",
    "PlanBudgets",
    "PlanError",
    "PlanQuestion",
    "Provenance",
    "ProviderProtocol",
    "RCAReport",
    "RankedCause",
    "RcaCliResult",
    "RcaOrchestrator",
    "RcaRunResult",
    "RcaToolRegistry",
    "RcaToolResult",
    "ReadExternalLogInput",
    "RegressionChange",
    "ReportConclusion",
    "RepositoryFingerprint",
    "RepositoryInventory",
    "RetrievalHints",
    "RetrievedCase",
    "RuntimeTestVerifier",
    "RuntimeVerificationSandbox",
    "SandboxCommandResult",
    "SourceLocation",
    "SourceSnippet",
    "SpecialistOutput",
    "SpecialistResponse",
    "SynthesisError",
    "TfidfModel",
    "Timing",
    "UncertaintyLevel",
    "UncertaintySummary",
    "Usage",
    "UsageTracker",
    "VerificationOutcome",
    "VerificationResult",
    "VerificationRun",
    "VerificationStatus",
    "VerificationStep",
    "add_rca_subparser",
    "aggregate_evidence",
    "assert_fingerprint_unchanged",
    "build_code_prompt",
    "build_final_report_prompt",
    "build_git_history_prompt",
    "build_history_index",
    "build_hypotheses_prompt",
    "build_incident_context",
    "build_issue_ci_prompt",
    "build_lead_prompt",
    "build_ranked_snippets",
    "build_repository_inventory",
    "build_tfidf",
    "capture_repository_fingerprint",
    "extract_signals",
    "import_corpus",
    "load_incident",
    "model_to_json",
    "render_rca_markdown",
    "resolve_base_commit",
    "run_rca_command",
    "run_rca_pipeline",
    "write_artifact",
]
