"""RootTrace RCA contracts and artifacts.

The Demo MVP keeps the internal ``patchpilot`` package namespace for
compatibility; RCA code lives under ``patchpilot.rca``. User-facing RCA
artifacts and documentation use the RootTrace name.
"""

from patchpilot.rca.artifacts import (
    ARTIFACT_EVIDENCE_GRAPH,
    ARTIFACT_HYPOTHESES,
    ARTIFACT_INCIDENT,
    ARTIFACT_INVESTIGATION_PLAN,
    ARTIFACT_RCA_REPORT,
    ARTIFACT_VERIFICATION,
    ArtifactError,
    ArtifactWriter,
    model_to_json,
    write_artifact,
)
from patchpilot.rca.context import (
    ContextTruncation,
    IncidentContext,
    IncidentSignals,
    RepositoryFingerprint,
    RepositoryInventory,
    SourceSnippet,
)
from patchpilot.rca.context_builder import (
    assert_fingerprint_unchanged,
    build_incident_context,
    build_ranked_snippets,
    build_repository_inventory,
    capture_repository_fingerprint,
    extract_signals,
)
from patchpilot.rca.incident_loader import (
    LoadedIncident,
    load_incident,
    resolve_base_commit,
)
from patchpilot.rca.sandbox import (
    RuntimeVerificationSandbox,
    SandboxCommandResult,
)
from patchpilot.rca.schema import (
    AgentFinding,
    AgentRole,
    CauseLink,
    ConfidenceLevel,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceItem,
    EvidenceKind,
    EvidenceRelation,
    FindingStatus,
    FixRecommendation,
    Hypothesis,
    HypothesisDisposition,
    IncidentInput,
    InvestigationPlan,
    PlanBudgets,
    PlanQuestion,
    Provenance,
    RankedCause,
    RCAReport,
    RegressionChange,
    ReportConclusion,
    SourceLocation,
    Timing,
    UncertaintyLevel,
    UncertaintySummary,
    Usage,
    VerificationOutcome,
    VerificationResult,
    VerificationStatus,
    VerificationStep,
)
from patchpilot.rca.tools import (
    GitBlameInput,
    GitHistoryInput,
    GitShowInput,
    InspectSymbolsInput,
    RcaToolRegistry,
    RcaToolResult,
    ReadExternalLogInput,
)

__all__ = [
    "ARTIFACT_EVIDENCE_GRAPH",
    "ARTIFACT_HYPOTHESES",
    "ARTIFACT_INCIDENT",
    "ARTIFACT_INVESTIGATION_PLAN",
    "ARTIFACT_RCA_REPORT",
    "ARTIFACT_VERIFICATION",
    "AgentFinding",
    "AgentRole",
    "ArtifactError",
    "ArtifactWriter",
    "CauseLink",
    "ConfidenceLevel",
    "ContextTruncation",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceRelation",
    "FindingStatus",
    "FixRecommendation",
    "GitBlameInput",
    "GitHistoryInput",
    "GitShowInput",
    "Hypothesis",
    "HypothesisDisposition",
    "IncidentContext",
    "IncidentInput",
    "IncidentSignals",
    "InspectSymbolsInput",
    "InvestigationPlan",
    "LoadedIncident",
    "PlanBudgets",
    "PlanQuestion",
    "Provenance",
    "RCAReport",
    "RankedCause",
    "RcaToolRegistry",
    "RcaToolResult",
    "ReadExternalLogInput",
    "RegressionChange",
    "ReportConclusion",
    "RepositoryFingerprint",
    "RepositoryInventory",
    "RuntimeVerificationSandbox",
    "SandboxCommandResult",
    "SourceLocation",
    "SourceSnippet",
    "Timing",
    "UncertaintyLevel",
    "UncertaintySummary",
    "Usage",
    "VerificationOutcome",
    "VerificationResult",
    "VerificationStatus",
    "VerificationStep",
    "assert_fingerprint_unchanged",
    "build_incident_context",
    "build_ranked_snippets",
    "build_repository_inventory",
    "capture_repository_fingerprint",
    "extract_signals",
    "load_incident",
    "model_to_json",
    "resolve_base_commit",
    "write_artifact",
]
